package co.luism.ksoft.iot.utils.configuration;

/**
 * Created by luis on 15.10.14.
 */
public enum ReturnCode {
    OK,
    ODS_FAHRZEUGE_NOT_FOUND, ODS_BUFFER_NOT_FOUND,
    ODS_KATEGORIEN_NOT_FOUND, RTS_CONFIG_NOT_FOUND, ODS_NO_Werkstatttext, ODS_WRONG_HARDWARE_TYPE,
    ODS_LOG_SIZE_NOT_PARSABLE, ODS_SAMPLING_INTERVAL_NOT_PARSABLE, ODS_RINGBUFFER_SETTING_NOT_READ,
    ODS_SERVER_PORT_NOT_PARSABLE, ODS_MAXBUFFER_SIZE_REACHED, ODS_MAX_CATEGORY_REACHED,
    ODS_SIGNED_FIELD_NOT_VALID, ODS_UNITS_NOT_FOUND, ODS_EVENT_NOT_EXIST, NOK, XML_ERROR_READ_DOM,
    XML_FILE_NOT_FOUND, XML_FAIL_TO_READ_PROPERTIES, XML_FAIL_TO_READ_LOGGER, XML_PORT_NUMBER_FORMAT_EXCEPTION,
    XML_HARDWARE_TYPE_NOT_FOUND, XML_DATA_TAG_WITHOUT_NAME_ID, XML_DATA_TAG_TYPE_INVALID, XML_DATA_TAG_UNIT_INVALID,
    XML_DATA_TAG_TYPE_SIGNED_PROPERTY_NOT_VALID, XML_INVALID_INTERFACE, XML_READ_LOGGER_INVALID_NUMERIC_FORMAT,
    XML_BUFFER_PARAMETERS_NUMBER_FORMAT_ERROR, XML_CATEGORY_WITHOUT_NAME, XML_CATEGORY_WITH_WRONG_BUFFER_ID,
    XML_CATEGORY_BUFFER_ID_NOT_A_NUMBER, XML_CATEGORY_INDEX_OUT_OF_BOUNDS, XML_CATEGORY_DATA_TAG_VALUE_NOT_FOUND,
    XML_EVENT_WITHOUT_NAME, XML_EVENT_WITHOUT_UIC_CATEGORY, XML_EVENT_WITHOUT_MAX_NUMBER_ENTRIES,
    XML_EVENT_MAX_NUMBER_ENTRIES_NOT_A_NUMBER, ODS_VEHICLE_COULD_NOT_BE_CREATED, ODS_TITLE_NOT_FOUND
}
